# Generated by Django 3.2.23 on 2024-01-15 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, default='../default_post_pfyxaa', upload_to='images/'),
        ),
    ]
