# Generated by Django 3.2.23 on 2024-01-17 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='teacher',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
